# --- !Ups

create table if not exists priority(
    id bigint generated by default as identity(start with 1) not null primary key,
    title varchar not null,
    color text not null
);

# --- !Downs
drop table priority cascade;