# --- !Ups

create table if not exists users(
    id bigint generated by default as identity(start with 1) not null primary key,
    firstname varchar not null,
    lastname varchar not null,
    email varchar not null,
    password varchar not null,
    phone varchar not null,
    telegram varchar null,
    created timestamp not null,
    updated timestamp null,
    deleted timestamp null,
    unique(email, telegram)
);

# --- !Downs
drop table users cascade;