# --- !Ups

create table if not exists users(
    id bigint generated by default as identity(start with 1) not null primary key,
    first_name varchar not null,
    last_name varchar not null,
    email varchar not null,
    password varchar not null,
    phone varchar not null,
    created timestamp not null,
    updated timestamp not null,
    deleted timestamp null,
    unique(email, telegram)
);

# --- !Downs
drop table users cascade;