# --- !Ups

create table if not exists tasktype(
    id bigint generated by default as identity(start with 1) not null primary key,
    title varchar not null,
    user_id bigint not null,
    CONSTRAINT FKTaskType_user FOREIGN KEY
    (user_id) REFERENCES users(id),
    parent_id bigint not null,
    CONSTRAINT FKTaskType_parent FOREIGN KEY
    (id) REFERENCES tasktype(id),
    created date not null,
    updated date null,
    deleted date null
);

# --- !Downs
drop table typetask cascade;