# --- !Ups

create table if not exists task_type(
    id bigint generated by default as identity(start with 1) not null primary key,
    title varchar not null,
    user_id bigint not null,
    CONSTRAINT fk_task_type_user FOREIGN KEY
    (user_id) REFERENCES users(id),
    parent_id bigint not null,
    CONSTRAINT fk_task_type_parent FOREIGN KEY
    (id) REFERENCES task_type(id),
    created timestamp not null,
    updated timestamp null,
    deleted timestamp null
);

# --- !Downs
drop table task_type cascade;