# --- !Ups

create table if not exists task(
    id bigint generated by default as identity(start with 1) not null primary key,
    title varchar not null,
    description text null,
    priority_id bigint not null,
    task_type_id bigint null,
    CONSTRAINT fk_task_task_type FOREIGN KEY
    (task_type_id) REFERENCES task_type(id),
    CONSTRAINT fk_task_priority_id FOREIGN KEY
    (priority_id) REFERENCES priority(id),
    due_date timestamp not null,
    created timestamp not null,
    updated timestamp not null,
    deleted timestamp null
);

# --- !Downs
drop table task cascade;