# --- !Ups

create table if not exists task(
    id bigint generated by default as identity(start with 1) not null primary key,
    title varchar not null,
    description text null,
    tasktype_id bigint not null,
    CONSTRAINT FKTask_tasktype FOREIGN KEY
    (tasktype_id) REFERENCES tasktype(id),
    due_date date not null,
    created date not null,
    updated date null,
    deleted date null
);

# --- !Downs
drop table task cascade;