# --- !Ups

create table if not exists user_session(
    id bigint generated by default as identity(start with 1) not null primary key,
    session_id varchar not null,
    user_id bigint not null,
    is_active boolean not null,
    created timestamp not null
);

# --- !Downs
drop table user_session cascade;